baseURL = "https://aidanmeacham.com"
title = "Aidan Meacham"
copyright = ""

theme = "minimo"

disablePathToLower = true

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "PhD Candidate, Paris // Acoustic Engineer, San Francisco"
  dateFormat = "2006, Jan 2"
  # copyrightOwner = "Aidan Meacham"
  # copyrightStartYear = "2017"
  # favicon = "favicon.ico"
  # hideEntryNavigation = false
  # customCSS = ["css/custom.css"]
  # customJS = ["js/custom.js"]
  # hideSocialMenu = false
  # showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

# [params.opengraph]
#   [params.opengraph.facebook]
#     admins = ""
#     appid = ""

# [taxonomies]
#   category = "categories"
#   tag = "tags"

# [social]
#   facebook = ""

[author]
  name = "Aidan Meacham"

[author.social]
  # codepen = ""
  email = "contact@aidanmeacham.com"
  # facebook = ""
  github = "1ceaham"
  # instagram = "instagram"
  # twitter = ""
  # linkedin = ""

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "home"
  url = "https://aidanmeacham.com"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
